openapi: 3.0.1
info:
  title: Example Payment Gateway API
  version: 0.0.1
  description: Example Payment Gateway API Documentation
servers:
  - url: 'localhost/v1/'
    
paths:
  /authorize:
    description: 'Authorize'
    post:
      requestBody:
        description: Credit Card Authorization
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApproveRequest'
              
      responses:
        '200':
          description: Success Authorize.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApproveResponse'
  /void:
    description: 'Void previous Authorization'
    post:
      requestBody:
        description: Void previous Authorization
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoidRequest'
              
      responses:
        '200':
          description: Success Authorize.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrasResponse'
                

  /capture:
    description: 'Capture Amount'
    post:
      requestBody:
        description: Capture Amount
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaptureRefundRequest'
              
      responses:
        '200':
          description: Success Authorize.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrasResponse'                


  /refund:
    description: 'Refund Amount'
    post:
      requestBody:
        description: Refund Amount
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaptureRefundRequest'
              
      responses:
        '200':
          description: Success Authorize.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrasResponse' 
 
  
components:
  schemas:
        
    ApproveRequest:
      type: object
      properties:
        merchant_key:
          type: string
          example: 'KEY1'
        cc_number:
          type: string
          example: '4000000000000000'
        cc_cvv:
          type: string
          example: '1234'
        cc_month:
          type: string
          example: '12'          
        cc_year:
          type: string
          example: '2025'          
        currency:
          type: string
          example: 'USD'          
        amount:
          type: string
          example: '100'          

    VoidRequest:
      type: object
      properties:
        approve_key:
          type: string
          example: 'YTGHGHGGREJHJHRJEHRJEHRJE'
        
    CaptureRefundRequest:
      type: object
      properties:
        approve_key:
          type: string
          example: 'YTGHGHGGREJHJHRJEHRJEHRJE'
        amount:
          type: string
          example: '10'
          
          
    ApproveResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            approved_amount_balance: 
              type: string
            approve_key: 
              type: string
            currency: 
              type: string
        result:
          type: string
                    
    TrasResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            approved_amount_balance: 
              type: string
            currency: 
              type: string
        result:
          type: string                    
    
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: ApiKey
    frontendURL:
      type: apiKey
      in: header
      name: FrontendURL
    token:
      type: apiKey
      in: header
      name: Token
      
security:
- apiKey: []    
- frontendURL: []
- token: []
          
          
          

